[build]
  command = "npm install" # Or "yarn install" if you use yarn
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[[redirects]]
  from = "/top-langs/*"
  to = "/.netlify/functions/top-langs"
  status = 200
  force = true

[[redirects]]
  from = "/pin/*"
  to = "/.netlify/functions/pin"
  status = 200
  force = true

[[redirects]]
  from = "/gist/*"
  to = "/.netlify/functions/gist"
  status = 200
  force = true

[[redirects]]
  from = "/wakatime/*"
  to = "/.netlify/functions/wakatime"
  status = 200
  force = true

[[redirects]]
  from = "/status/pat-info/*" # Match the path for pat-info
  to = "/.netlify/functions/status-pat-info" # Point to the generated function name
  status = 200
  force = true

[[redirects]]
  from = "/status/up/*" # Match the path for up
  to = "/.netlify/functions/status-up" # Point to the generated function name
  status = 200
  force = true

# Optional: If you want a default page at the root (e.g., a README.md rendered to index.html)
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200
